---
- name: install apache2 and service enablement
  hosts: infra1
  become: true
  tasks:
  ###
  - name:  update cache
  apt:
  update_cache: yes
  ###
  - name: install apache2
  apt:
  name: apache2
  state: present
  ###
  - name: start apache2 service
  service:
  name: apache2
  state: started
  enabled: true
