- name: Check and debug Apache service status
  hosts: infra1
  become: yes
  tasks:
    - name: Gather service facts
      ansible.builtin.service_facts:

    - name: Debug Apache2 service status
      ansible.builtin.debug:
        var: ansible_facts.services['apache2.service'] 
